# Generated by Django 4.2.1 on 2023-05-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='imagem',
            field=models.ImageField(null=True, upload_to='capa'),
        ),
    ]
